//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public long AdvertisementId { get; set; }
        public string LinkUrl { get; set; }
        public string HImageUrl { get; set; }
        public string VImageUrl { get; set; }
    }
}
