//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartDetail
    {
        public long CartDetailId { get; set; }
        public long ContactId { get; set; }
        public string CartCookie { get; set; }
        public int Quantity { get; set; }
        public long ProductId { get; set; }
        public double MRP { get; set; }
        public double Price { get; set; }
        public double TAX { get; set; }
        public string OfferTitle { get; set; }
        public double Discount { get; set; }
        public string SizeName { get; set; }
        public long ColorId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedDateInt { get; set; }
        public Nullable<int> UpdatedDateInt { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Product Product { get; set; }
    }
}
