//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterData
    {
        public long FilterDataId { get; set; }
        public long CategoryId { get; set; }
        public long FilterTitleId { get; set; }
        public string FilterName { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual FilterTitle FilterTitle { get; set; }
    }
}
