//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public long OfferId { get; set; }
        public string Title { get; set; }
        public Nullable<long> DiscountId { get; set; }
        public Nullable<long> DiscountPercentage { get; set; }
        public Nullable<long> FlatDiscount { get; set; }
        public Nullable<long> SpecificItems { get; set; }
        public Nullable<long> SpecificValue { get; set; }
    
        public virtual DiscountType DiscountType { get; set; }
    }
}
