//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPTE
    {
        public long id { get; set; }
        public string word { get; set; }
        public string meaning { get; set; }
        public string extrainfomation { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public bool isUpdated { get; set; }
    }
}
